#Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  - pwsh: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  # Get the latest stable version of Node.js or io.js
  - pwsh: Install-Product node $env:nodejs_version
  # install modules
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn run specs

# Don't actually build.
build: off

